handpoint/cordova-plugin-handpoint

- package.json
- plugin.xml
- src/ios/TransactionResult.m
Plugin updated to version 0.3.5.
Fixed error on iOS plugin when any receipt is null.
> HE-110 refund issue

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
- Fix [EFTCLIENT-3314](https://handpoint.atlassian.net/browse/EFTCLIENT-3314): Paysafe issue : differentiate positive and negative operations in txn history
> Eftclient 3314

- plugin.xml
- src/android/pax.gradle
Support bluetooth device scan in Android 10.
> HS-2022-BluetoothAndroid10

- plugin.xml
- src/android/com/handpoint/cordova/HandpointApiCordova.java
- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
- www/handpoint.js
- Fix [EFTCLIENT-3635](https://handpoint.atlassian.net/browse/EFTCLIENT-3635): Wifi change is not handled correctly through SmartPOS.
The problem is Android needs location services to be enabled in order to get wifi scan results: 
- We are showing now the settings/location screen if not enabled
- When no networks are found show a guide on how to connect to the wifi
> EFTCLIENT-3635

- src/android/com/handpoint/cordova/HandpointHelper.java
- Fix [EFTCLIENT-3655](https://handpoint.atlassian.net/browse/EFTCLIENT-3655): Listen to printer events
> EFTCLIENT-3655

- src/android/com/handpoint/cordova/HandpointHelper.java
Preferred card language should not come as a status message but a field in the events and in the transaction result.
> EFTCLIENT-3968

- src/android/com/handpoint/cordova/HandpointHelper.java
Implement the usage of the physical keyboard on the A80.
> EFTCLIENT-4137

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
Align all the methods in _HandpointHelper_ to handle _TransactionStartResult_ object:
- Use _OperationStartResult_ instead of _TransactionStartResult_
> EFTCLIENT-4627

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
fix: use of SDK methods to check if the device has specific modules.
> EFTCLIENT-4709

- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
- www/handpoint.js
* feat: check if the device has a specific module
> 4.0.2ToMain

- package.json
- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
> EFTCLIENT-4791

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
feat: include pre-auth operations
> EFTCLIENT-4794

- plugin.xml
- src/android/pax.gradle
- fix: Adding mPOS support for Android >= 12
> EFTCLIENT-4849

- .github/workflows/increment-rc.yml
* feat: Added GHA Increment RC
> feat: Adedd GHA increment RC

- src/android/com/handpoint/cordova/HandpointHelper.java
fix: adding support for GTS transactionReference in preAuthotization method
> EFTCLIENT-4913

- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
- www/handpoint.js
- adding a new method `automaticRefund` to perform refunds without any card detail
> EFTCLIENT-4938

- plugin.xml
- src/android/pax.gradle
> EFTCLIENT-4971

- src/android/com/handpoint/cordova/HandpointApiCordova.java
- Introduced an ExecutorService as a field in the HandpointApiCordova class to manage background execution.
- Modified the execute method to use the ExecutorService for printDetailedLog action calls, ensuring these calls are processed in a background thread.
- Improved UI Responsiveness: By offloading printDetailedLog execution to a background thread, the UI thread remains unblocked, leading to smoother user interactions.
- Resource Efficiency: Utilizing a single background thread for multiple tasks reduces the overhead associated with thread management, enhancing the app's overall performance.
> EFTCLIENT-4973

- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
- www/handpoint.js
> EFTCLIENT-5015

- src/android/com/handpoint/cordova/HandpointHelper.java
- feat: adding log traces that allow us to measure the performance of different parts of the PLM flow
> EFTCLIENT-5078

- src/android/com/handpoint/cordova/HandpointHelper.java
- feat: implement Events.ReceiptUploadingEvent interface. add guid to r…eceiptsReady event
> EFTCLIENT-5093

- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/pax.gradle
- www/handpoint.js
fix: compilation errors due to changes in interfaces (usbDevice and connectionManager)
> EFTCLIENT-5083

- src/android/com/handpoint/cordova/HandpointHelper.java
fix: undo changes in interface (usb device)
> EFTCLIENT-5112

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
> EFTCLIENT-5099

- src/android/com/handpoint/cordova/HandpointHelper.java
- src/android/com/handpoint/cordova/SysManagerWrapper.java
- www/handpoint.js
feat: methods to enable/disable screensaver
> EFTCLIENT-5153

- src/android/com/handpoint/cordova/HandpointHelper.java
- feat: Support cloud command setScreenBrightness see [https://github.com/handpoint/hipos-app/pull/1025](https://github.com/handpoint/hipos-app/pull/1025)
> EFTCLIENT-5152

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
feat: support for enable/disable volume controls
> EFTCLIENT-5162

- src/android/com/handpoint/cordova/HandpointHelper.java
- www/handpoint.js
> EFTCLIENT-5187

- package.json
- src/android/pax.gradle
chore: manual update SDK version 7.1008.7-RC.0
> chore: manual update to version 4.8.5-RC.3

- src/android/pax.gradle
Update pax.gradle to change imports
> SDK-3525-2
